name: ci
on:
  push:
    branches:
      - main
      - release/**
  pull_request:

jobs:
  lint:
    name: "Linting"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - run: make develop
      - run: make lint
      - run: make format
      - run: git diff --quiet || (echo '::error ::lint produced file changes, run linter locally and try again' && exit 1)
  test:
    name: "Tests"

    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      max-parallel: 4
      matrix:
        redis-py: [4.*]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install redis-cli
        run: sudo apt-get install redis-tools
      - run: make develop
      - run: make redis-cluster
      - run: pip install redis==${{ matrix.redis-py }}
      - run: make test
